
YAHOO.lang.augmentObject(YAHOO.yui.moduleMeta, {
"inputex":{name:"inputEx", type: "inputEx-Core"},
"inputex-autocomplete":{name:"inputEx Autocomplete Field", type: "inputEx-Field"},
"inputex-birthdatefield":{name:"inputEx Birthdate Field", type: "inputEx-Field"},
"inputex-button":{name:"inputEx Button Widget", type: "inputEx-Widget"},
"inputex-checkbox":{name:"inputEx Checkbox Field", type: "inputEx-Field"},
"inputex-choice":{name:"inputEx Choice Mixin", type: "inputEx-Mixin"},
"inputex-colorfield":{name:"inputEx Color Field", type: "inputEx-Field"},
"inputex-colorpickerfield":{name:"inputEx ColorPicker Field", type: "inputEx-Field"},
"inputex-combinefield":{name:"inputEx Combine Field", type: "inputEx-Field"},
"inputex-css":{name:"inputEx CSS", type: "inputEx-Core"},
"inputex-datatable":{name:"inputEx Datatable", type: "inputEx-Widget"},
"inputex-datefield":{name:"inputEx Date Field", type: "inputEx-Field"},
"inputex-datepickerfield":{name:"inputEx DatePicker Field", type: "inputEx-Field"},
"inputex-dateselectmonthfield":{name:"inputEx DateSelectMonth Field", type: "inputEx-Field"},
"inputex-datesplitfield":{name:"inputEx DateSplit Field", type: "inputEx-Field"},
"inputex-datetimefield":{name:"inputEx DateTime Field", type: "inputEx-Field"},
"inputex-ddlist":{name:"inputEx DDList widget", type: "inputEx-Widget"},
"inputex-dialog":{name:"inputEx Dialog widget", type: "inputEx-Widget"},
"inputex-dsselectfield":{name:"inputEx DSSelect Field", type: "inputEx-Field"},
"inputex-emailfield":{name:"inputEx Email Field", type: "inputEx-Field"},
"inputex-field":{name:"inputEx Field Core", type: "inputEx-Core"},
"inputex-form":{name:"inputEx Form", type: "inputEx-Field"},
"inputex-group":{name:"inputEx Group", type: "inputEx-Field"},
"inputex-hiddenfield":{name:"inputEx Hidden Field", type: "inputEx-Field"},
"inputex-inplaceedit":{name:"inputEx InPlaceEdit Field", type: "inputEx-Field"},
"inputex-inplace-datatable":{name:"inputEx InPlaceEdit datatable", type: "inputEx-Widget"},
"inputex-integerfield":{name:"inputEx Integer Field", type: "inputEx-Field"},
"inputex-ipv4field":{name:"inputEx IPv4 Field", type: "inputEx-Field"},
"inputex-jsonschema":{name:"inputEx JSON-Schema utilities", type: "inputEx-Utils"},
"inputex-jsontreeinspector":{name:"inputEx JSON-tree-inspector", type: "inputEx-Widget"},
"inputex-keyvaluefield":{name:"inputEx KeyValue Field", type: "inputEx-Field"},
"inputex-keyopvaluefield":{name:"inputEx KeyOpValue Field", type: "inputEx-Field"},
"inputex-lang-fr":{name:"inputEx French Locale", type: "inputEx-Locale"},
"inputex-lang-it":{name:"inputEx Italian Locale", type: "inputEx-Locale"},
"inputex-lang-nl":{name:"inputEx NL Locale", type: "inputEx-Locale"},
"inputex-lang-es":{name:"inputEx Spanish Locale", type: "inputEx-Locale"},
"inputex-lang-de":{name:"inputEx Deutsch Locale", type: "inputEx-Locale"},
"inputex-lens":{name:"inputEx Lens field", type: "inputEx-Field"},
"inputex-listfield":{name:"inputEx List Field", type: "inputEx-Field"},
"inputex-mapfield":{name:"inputEx Map Field", type: "inputEx-Field"},
"inputex-multiautocomplete":{name:"inputEx MultiAutocomplete Field", type: "inputEx-Field"},
"inputex-multiselectfield":{name:"inputEx MultiSelect Field", type: "inputEx-Field"},
"inputex-numberfield":{name:"inputEx Number Field", type: "inputEx-Field"},
"inputex-passwordfield":{name:"inputEx Password Field", type: "inputEx-Field"},
"inputex-radiofield":{name:"inputEx Radio Field", type: "inputEx-Field"},
"inputex-rpc":{name:"inputEx RPC utilities", type: "inputEx-Utils"},
"inputex-rtefield":{name:"inputEx Rich Text Editing field", type: "inputEx-Field"},
"inputex-selectfield":{name:"inputEx Select field", type: "inputEx-Field"},
"inputex-sliderfield":{name:"inputEx Slider field", type: "inputEx-Field"},
"inputex-smdtester":{name:"inputEx SMD Tester", type: "inputEx-Utils"},
"inputex-stringfield":{name:"inputEx String field", type: "inputEx-Field"},
"inputex-textarea":{name:"inputEx Textarea field", type: "inputEx-Field"},
"inputex-timefield":{name:"inputEx Time field", type: "inputEx-Field"},
"inputex-timeintervalfield":{name:"inputEx TimeInterval field", type: "inputEx-Field"},
"inputex-treefield":{name:"inputEx Tree field", type: "inputEx-Field"},
"inputex-typefield":{name:"inputEx Type field", type: "inputEx-Field"},
"inputex-uneditable":{name:"inputEx Uneditable field", type: "inputEx-Field"},
"inputex-urlfield":{name:"inputEx URL field", type: "inputEx-Field"},
"inputex-vectorfield":{name:"inputEx Vector field", type: "inputEx-Field"},
"inputex-visus":{name:"inputEx Visualization utilities", type: "inputEx-Utils"},
"inputex-yql":{name:"inputEx YQL utilities", type: "inputEx-Utils"}
});
