[theme]
inherit = basic
stylesheet = spiffworks.css
sidebars =

[options]
navigation_depth = 4
collapse_navigation = false
includehidden = true
titles_only = false
logo_only = false
prev_next_buttons_location = bottom
style_external_links = false
vcs_pageview_mode =
sticky_navigation = true
